# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-04 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='latLon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.IntegerField()),
                ('altitude', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('temp', models.FloatField()),
                ('humidity', models.FloatField()),
                ('ghi', models.FloatField()),
                ('dni', models.FloatField()),
                ('dhi', models.FloatField()),
                ('infra', models.FloatField()),
                ('windSpeed', models.FloatField()),
                ('windDirection', models.FloatField()),
                ('pressure', models.FloatField()),
            ],
        ),
    ]
