# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-05 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0002_auto_20190304_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turbines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('cutIn', models.FloatField()),
                ('ratedSpeed', models.FloatField()),
                ('p1', models.FloatField()),
                ('p2', models.FloatField()),
                ('p3', models.FloatField()),
                ('p4', models.FloatField()),
                ('p5', models.FloatField()),
            ],
        ),
    ]
