# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-05 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0003_turbines'),
    ]

    operations = [
        migrations.AddField(
            model_name='turbines',
            name='cutOut',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
