# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-05 16:09
from __future__ import unicode_literals

from django.db import migrations
from django.apps import apps
import pandas as pd

def populateTurbines(apps, schema_editor):
    Turbines = apps.get_model('generation', 'Turbines')
    dataTurbines = pd.read_csv(r'turbines.csv', header=None).as_matrix()

    for i in range(0, len(dataTurbines)):
        t=Turbines(manufacturer=dataTurbines[i,0], rating=dataTurbines[i,1], cutIn=dataTurbines[i,2], ratedSpeed=dataTurbines[i,3],cutOut=dataTurbines[i,4], p1=dataTurbines[i,5], p2=dataTurbines[i,6], p3=dataTurbines[i,7], p4=dataTurbines[i,8], p5=dataTurbines[i,9])
        t.save()
        
class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0004_turbines_cutout'),
    ]

    operations = [
        migrations.RunPython(populateTurbines)
    ]
