from django.db import models

# Create your models here.

class gspStats(models.Model):
    index=models.IntegerField()
    rating=models.IntegerField()
    lat=models.FloatField()
    lon=models.FloatField()
    totalHouses=models.IntegerField()
    detached=models.IntegerField()
    semiD=models.IntegerField()
    terraced=models.IntegerField()
    flat=models.IntegerField()
    totCars=models.IntegerField()
    noCH=models.IntegerField()
    gas=models.IntegerField()
    electric=models.IntegerField()
    oil=models.IntegerField()
    solid=models.IntegerField()
    other=models.IntegerField()


class primarySSEStats(models.Model):
    index = models.IntegerField()
    name = models.CharField(max_length=100)
    gsp = models.IntegerField()
    rating = models.FloatField(null=True)
    customers = models.IntegerField(null=True)

class windFES(models.Model):
    index = models.IntegerField()
    scenario = models.IntegerField()
    year18 = models.FloatField()
    year19 = models.FloatField()
    year20 = models.FloatField()
    year21 = models.FloatField()
    year22 = models.FloatField()
    year23 = models.FloatField()
    year24 = models.FloatField()
    year25 = models.FloatField()
    year26 = models.FloatField()
    year27 = models.FloatField()
    year28 = models.FloatField()
    year29 = models.FloatField()
    year30 = models.FloatField()
    year31 = models.FloatField()
    year32 = models.FloatField()
    year33 = models.FloatField()
    year34 = models.FloatField()
    year35 = models.FloatField()
    year36 = models.FloatField()
    year37 = models.FloatField()
    year38 = models.FloatField()
    year39 = models.FloatField()
    year40 = models.FloatField()

class pvFES(models.Model):
    index = models.IntegerField()
    scenario = models.IntegerField()
    year18 = models.FloatField()
    year19 = models.FloatField()
    year20 = models.FloatField()
    year21 = models.FloatField()
    year22 = models.FloatField()
    year23 = models.FloatField()
    year24 = models.FloatField()
    year25 = models.FloatField()
    year26 = models.FloatField()
    year27 = models.FloatField()
    year28 = models.FloatField()
    year29 = models.FloatField()
    year30 = models.FloatField()
    year31 = models.FloatField()
    year32 = models.FloatField()
    year33 = models.FloatField()
    year34 = models.FloatField()
    year35 = models.FloatField()
    year36 = models.FloatField()
    year37 = models.FloatField()
    year38 = models.FloatField()
    year39 = models.FloatField()
    year40 = models.FloatField()

class storageFES(models.Model):
    index = models.IntegerField()
    scenario = models.IntegerField()
    year18 = models.FloatField()
    year19 = models.FloatField()
    year20 = models.FloatField()
    year21 = models.FloatField()
    year22 = models.FloatField()
    year23 = models.FloatField()
    year24 = models.FloatField()
    year25 = models.FloatField()
    year26 = models.FloatField()
    year27 = models.FloatField()
    year28 = models.FloatField()
    year29 = models.FloatField()
    year30 = models.FloatField()
    year31 = models.FloatField()
    year32 = models.FloatField()
    year33 = models.FloatField()
    year34 = models.FloatField()
    year35 = models.FloatField()
    year36 = models.FloatField()
    year37 = models.FloatField()
    year38 = models.FloatField()
    year39 = models.FloatField()
    year40 = models.FloatField()

class subWindFES(models.Model):
    index = models.IntegerField()
    scenario = models.IntegerField()
    year18 = models.FloatField()
    year19 = models.FloatField()
    year20 = models.FloatField()
    year21 = models.FloatField()
    year22 = models.FloatField()
    year23 = models.FloatField()
    year24 = models.FloatField()
    year25 = models.FloatField()
    year26 = models.FloatField()
    year27 = models.FloatField()
    year28 = models.FloatField()
    year29 = models.FloatField()
    year30 = models.FloatField()
    year31 = models.FloatField()
    year32 = models.FloatField()
    year33 = models.FloatField()
    year34 = models.FloatField()
    year35 = models.FloatField()
    year36 = models.FloatField()
    year37 = models.FloatField()
    year38 = models.FloatField()
    year39 = models.FloatField()
    year40 = models.FloatField()

class subPVFES(models.Model):
    index = models.IntegerField()
    scenario = models.IntegerField()
    year18 = models.FloatField()
    year19 = models.FloatField()
    year20 = models.FloatField()
    year21 = models.FloatField()
    year22 = models.FloatField()
    year23 = models.FloatField()
    year24 = models.FloatField()
    year25 = models.FloatField()
    year26 = models.FloatField()
    year27 = models.FloatField()
    year28 = models.FloatField()
    year29 = models.FloatField()
    year30 = models.FloatField()
    year31 = models.FloatField()
    year32 = models.FloatField()
    year33 = models.FloatField()
    year34 = models.FloatField()
    year35 = models.FloatField()
    year36 = models.FloatField()
    year37 = models.FloatField()
    year38 = models.FloatField()
    year39 = models.FloatField()
    year40 = models.FloatField()

class subStorageFES(models.Model):
    index = models.IntegerField()
    scenario = models.IntegerField()
    year18 = models.FloatField()
    year19 = models.FloatField()
    year20 = models.FloatField()
    year21 = models.FloatField()
    year22 = models.FloatField()
    year23 = models.FloatField()
    year24 = models.FloatField()
    year25 = models.FloatField()
    year26 = models.FloatField()
    year27 = models.FloatField()
    year28 = models.FloatField()
    year29 = models.FloatField()
    year30 = models.FloatField()
    year31 = models.FloatField()
    year32 = models.FloatField()
    year33 = models.FloatField()
    year34 = models.FloatField()
    year35 = models.FloatField()
    year36 = models.FloatField()
    year37 = models.FloatField()
    year38 = models.FloatField()
    year39 = models.FloatField()
    year40 = models.FloatField()

class hpFES(models.Model):
    index = models.IntegerField()
    scenario = models.IntegerField()
    year18 = models.FloatField()
    year19 = models.FloatField()
    year20 = models.FloatField()
    year21 = models.FloatField()
    year22 = models.FloatField()
    year23 = models.FloatField()
    year24 = models.FloatField()
    year25 = models.FloatField()
    year26 = models.FloatField()
    year27 = models.FloatField()
    year28 = models.FloatField()
    year29 = models.FloatField()
    year30 = models.FloatField()
    year31 = models.FloatField()
    year32 = models.FloatField()
    year33 = models.FloatField()
    year34 = models.FloatField()
    year35 = models.FloatField()
    year36 = models.FloatField()
    year37 = models.FloatField()
    year38 = models.FloatField()
    year39 = models.FloatField()
    year40 = models.FloatField()

class evFES(models.Model):
    index = models.IntegerField()
    scenario = models.IntegerField()
    year18 = models.FloatField()
    year19 = models.FloatField()
    year20 = models.FloatField()
    year21 = models.FloatField()
    year22 = models.FloatField()
    year23 = models.FloatField()
    year24 = models.FloatField()
    year25 = models.FloatField()
    year26 = models.FloatField()
    year27 = models.FloatField()
    year28 = models.FloatField()
    year29 = models.FloatField()
    year30 = models.FloatField()
    year31 = models.FloatField()
    year32 = models.FloatField()
    year33 = models.FloatField()
    year34 = models.FloatField()
    year35 = models.FloatField()
    year36 = models.FloatField()
    year37 = models.FloatField()
    year38 = models.FloatField()
    year39 = models.FloatField()
    year40 = models.FloatField()
    
