# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-21 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='industrialBreakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField()),
                ('GSP', models.IntegerField()),
                ('manufacturing', models.FloatField()),
                ('commercial', models.FloatField()),
                ('entertainment', models.FloatField()),
                ('education', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='industrialNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GSP', models.IntegerField()),
                ('manufacturing', models.IntegerField()),
                ('commercial', models.IntegerField()),
                ('entertainment', models.IntegerField()),
                ('education', models.IntegerField()),
            ],
        ),
    ]
