# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-21 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industrialbreakdown',
            name='commercial',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='industrialbreakdown',
            name='education',
            field=models.FloatField(null=True),
        ),
    ]
