# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-20 14:56
from __future__ import unicode_literals

from django.db import migrations
from django.apps import apps
import pandas as pd
import numpy as np

def populateIndustrialTables(apps, schema_editor):
    industrialBreakdown=apps.get_model('industry', 'industrialBreakdown')
    industrialNumbers=apps.get_model('industry', 'industrialNumbers')

    dataBreakdown = pd.read_csv(r'industryBreakdown.csv', header=None).as_matrix()
    dataNumbers = pd.read_csv(r'industryNumbers.csv', header=None).as_matrix()

    for i in range(0, len(dataBreakdown)):
        b=industrialBreakdown(hour=dataBreakdown[i,0], GSP=dataBreakdown[i,1],
                              manufacturing=dataBreakdown[i,2],
                              commercial=dataBreakdown[i,3],
                              entertainment=dataBreakdown[i,4],
                              education=dataBreakdown[i,5])
        b.save()

    for i in range(0, len(dataNumbers)):
        n=industrialNumbers(GSP=dataNumbers[i,0],
                            manufacturing=dataNumbers[i,1],
                            commercial=dataNumbers[i,2],
                            entertainment=dataNumbers[i,3],
                            education=dataNumbers[i,4])
        n.save()


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0003_auto_20190521_1008'),
    ]

    operations = [
        migrations.RunPython(populateIndustrialTables)
    ]
