# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-06 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField()),
                ('GSP', models.IntegerField()),
                ('f40', models.IntegerField(default=0)),
                ('f60', models.IntegerField(default=0)),
                ('f100', models.IntegerField(default=0)),
                ('f140', models.IntegerField(default=0)),
                ('f160', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GSP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='industrialHeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField()),
                ('GSP', models.IntegerField()),
                ('industrialHeatDemand', models.FloatField()),
            ],
        ),
    ]
