# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-19 18:32
from __future__ import unicode_literals

from django.db import migrations
from django.apps import apps
import pandas as pd
import numpy as np

def populateHeatTables(apps, schema_editor):
    Family = apps.get_model('heat','Family')
    
    dataHeat1 = pd.read_csv(r'residentialHeatV1.csv', header=None).as_matrix()
    dataHeat2 = pd.read_csv(r'residentialHeatV2.csv', header=None).as_matrix()
    dataHeat = np.concatenate((dataHeat1,dataHeat2), axis=0)
    
    
    for i in range(0,(len(dataHeat))):
        hF=Family(hour=dataHeat[i,0], GSP=dataHeat[i,1], f40=dataHeat[i,2], f60=dataHeat[i,3], f100=dataHeat[i,4], f140=dataHeat[i,5], f160=dataHeat[i,6] )
        hF.save()

class Migration(migrations.Migration):

    dependencies = [
        ('heat', '0002_auto_20190306_1544'),
    ]

    operations = [
                  migrations.RunPython(populateHeatTables)
    ]
