# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-13 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whole', '0002_gspstats_gas'),
    ]

    operations = [
        migrations.AddField(
            model_name='gspstats',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
