# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-16 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whole', '0004_auto_20190313_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='primarySSEStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('gsp', models.IntegerField()),
                ('rating', models.FloatField(null=True)),
                ('customers', models.IntegerField(null=True)),
            ],
        ),
    ]
