# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-06 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gspLocalAuthority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gsp', models.CharField(max_length=100)),
                ('localAuthority', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_journey', models.FloatField()),
                ('journey_distance', models.FloatField()),
                ('second_journey_distance', models.FloatField()),
                ('speed', models.FloatField()),
                ('localAuthority', models.CharField(max_length=100)),
                ('Area', models.CharField(max_length=100)),
                ('typeEV', models.CharField(max_length=100)),
            ],
        ),
    ]
