# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-06 16:10
from __future__ import unicode_literals

from django.db import migrations
from django.apps import apps
import pandas as pd

def populateTransportTables(apps, schema_editor):
    Journey = apps.get_model('transport', 'Journey')
    gspLocal = apps.get_model('transport', 'gspLocalAuthority')

    dataJourney =  pd.read_csv(r'evTransportData.csv', header=None).as_matrix()
    dataGspLocal = pd.read_csv(r'gspLocalAuthority.csv', header=None).as_matrix()

    for i in range(0, len(dataJourney)):
        j=Journey(start_journey=dataJourney[i,0],journey_distance=dataJourney[i,1], second_journey_distance=dataJourney[i,2], speed=dataJourney[i,3], localAuthority=dataJourney[i,4], Area=dataJourney[i,5], typeEV=dataJourney[i,6])
        j.save()

    for i in range(0, len(dataGspLocal)):
        g = gspLocal(gsp=dataGspLocal[i,0], localAuthority=dataGspLocal[i,1])
        g.save()


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populateTransportTables)
    ]
