# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-17 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='electricalGSP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField()),
                ('GSP', models.IntegerField()),
                ('electricalDemand', models.FloatField()),
            ],
        ),
    ]
