# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-17 11:18
from __future__ import unicode_literals

from django.db import migrations

from django.apps import apps
import pandas as pd


def populateElectricalGSP(apps, schema_editor):
    electricalGSP = apps.get_model('electrical', 'electricalGSP')
    dataElectrical = pd.read_csv(r'electricalGSP.csv', header=None).as_matrix()

    for i in range(0, len(dataElectrical)):
        h=electricalGSP(hour=dataElectrical[i,0], GSP=dataElectrical[i,1], electricalDemand=dataElectrical[i,2])
        h.save()
        

class Migration(migrations.Migration):

    dependencies = [
        ('electrical', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populateElectricalGSP)
    ]
