# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-16 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrical', '0002_auto_20190117_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='electricalPrimarySSE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField()),
                ('primary', models.IntegerField()),
                ('electricalDemand', models.FloatField()),
            ],
        ),
    ]
