# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-16 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrical', '0003_electricalprimarysse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricalprimarysse',
            name='electricalDemand',
            field=models.FloatField(null=True),
        ),
    ]
