# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-16 09:04
from __future__ import unicode_literals

from django.db import migrations

from django.apps import apps
import pandas as pd

def populatePrimarySSE(apps, schema_editor):
    electricalPrimarySSE = apps.get_model('electrical', 'electricalprimarySSE')
    dataPrimary1 = pd.read_csv(r'primaryDemandSSE1.csv', header=None).as_matrix()
    dataPrimary2 = pd.read_csv(r'primaryDemandSSE2.csv', header=None).as_matrix()
    dataPrimary3 = pd.read_csv(r'primaryDemandSSE3.csv', header=None).as_matrix()

    for i in range(0, len(dataPrimary1)):
        p1 = electricalPrimarySSE(hour=dataPrimary1[i,0], primary=dataPrimary1[i,1], electricalDemand=dataPrimary1[i,2])
        p1.save()

    for i in range(0, len(dataPrimary2)):
        p2 = electricalPrimarySSE(hour=dataPrimary2[i,0], primary=dataPrimary2[i,1], electricalDemand=dataPrimary2[i,2])
        p2.save()

    for i in range(0, len(dataPrimary3)):
        p3 = electricalPrimarySSE(hour=dataPrimary3[i,0], primary=dataPrimary3[i,1], electricalDemand=dataPrimary3[i,2])
        p3.save()

    
class Migration(migrations.Migration):

    dependencies = [
        ('electrical', '0004_auto_20190716_1040'),
    ]

    operations = [
        migrations.RunPython(populatePrimarySSE)
    ]
